# Fliflight Vanilla Plus v0.3 - Potato
# no fog + bloom + shadows + waving foliage + custom sky + horizon haze
shadowMapResolution=1024
shadowDistance=64.0
shadow.culling=true
shadowHardwareFiltering=false
sunPathRotation=0.0
